credentials:
  usernames:
    admin:
      email: admin@spitc.com
      name: Admin
      password: '$2b$12$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36WQoeG6Lruj3vjPGga31lW'  # password = spitc2025
    user1:
      email: user1@spitc.com
      name: User1
      password: '$2b$12$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36WQoeG6Lruj3vjPGga31lW'
cookie:
  expiry_days: 30
  key: random_signature_key
  name: random_cookie_name
preauthorized: []